x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  celestia-light-node:
    build:
      context: ./celestia-node
      dockerfile: ${CELESTIA_APP_DOCKERFILE}
      args:
        - USER=celestia
        - DAEMON_VERSION=${CELESTIA_NODE_VERSION:-v0.21.9}
        - DAEMON_HOME=/data
        - DAEMON_NAME=celestia
    image: celestia-light-node:local
    pull_policy: never
    restart: unless-stopped
    stop_grace_period: 5m
    environment:
      - CELESTIA_NODE_TYPE=light
      - P2P_PORT=${CELESTIA_NODE_P2P_PORT:-2121}
      - NETWORK=${NETWORK:-celestia}
      - EXTRAS=${CELESTIA_NODE_EXTRA_FLAGS}
      - MONIKER=${MONIKER}
      - CELESTIA_NODE_GRPC_IP=${CELESTIA_NODE_GRPC_IP:-127.0.0.1}
      - CELESTIA_NODE_GRPC_PORT=${CELESTIA_NODE_GRPC_PORT:-26658}
    ports:
      - "${CELESTIA_NODE_RPC_PORT}:${CELESTIA_NODE_RPC_PORT}"
      - "${CELESTIA_NODE_P2P_PORT:-2121}:${CELESTIA_NODE_P2P_PORT:-2121}/tcp"
      - "${CELESTIA_NODE_P2P_PORT:-2121}:${CELESTIA_NODE_P2P_PORT:-2121}/udp"
    <<: *logging
    volumes:
      - celestia-node-data:/data
      - ./keys/celestia-node:/data/keys
    entrypoint:
      - docker-entrypoint.sh
      - celestia
      - light
      - start
      - --node.store
      - /data
      - --core.ip
      - ${CELESTIA_NODE_GRPC_IP}
      - --core.port
      - ${CELESTIA_NODE_GRPC_PORT}
      - --rpc.port
      - ${CELESTIA_NODE_RPC_PORT}
      - --rpc.addr
      - "0.0.0.0"
      - --metrics
      - --metrics.endpoint=otel.celestia.observer
    labels:
      - traefik.enable=true
      - traefik.http.routers.${CELESTIA_NODE_HOST}.service=${CELESTIA_NODE_HOST}
      - traefik.http.routers.${CELESTIA_NODE_HOST}.entrypoints=websecure
      - traefik.http.routers.${CELESTIA_NODE_HOST}.rule=Host(`${CELESTIA_NODE_HOST}.${DOMAIN}`)
      - traefik.http.routers.${CELESTIA_NODE_HOST}.tls.certresolver=letsencrypt
      - traefik.http.services.${CELESTIA_NODE_HOST}.loadbalancer.server.port=${CELESTIA_NODE_RPC_PORT}

  import-celestia-node-key:
    profiles: ["tools"]
    image: ghcr.io/celestiaorg/celestia-node:${CELESTIA_NODE_VERSION:-v0.21.9}
    user: root
    environment:
      - MONIKER=${MONIKER}
      - MNEMONIC=${MNEMONIC}
      - NETWORK=${NETWORK}
      - CELESTIA_NODE_TYPE=light
    volumes:
      - ./keys/celestia-node:/data/keys:rw
    entrypoint: ["/bin/bash", "-c"]
    command: |
      echo "Starting key import..."
      echo "$MNEMONIC" | cel-key add "$MONIKER" --recover \
        --home /data \
        --node.type light \
        --keyring-dir /data/keys
      echo "Key import completed"

volumes:
  celestia-node-data:
