x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  celestia-server:
    image: ghcr.io/celestiaorg/nitro-das-celestia:v0.4.3
    restart: unless-stopped
    <<: *logging
    entrypoint:
      - /bin/celestia-server
      - --celestia.namespace-id
      - "00000d048007a33abfeb"
      - --rpc-addr
      - "0.0.0.0"
      - --rpc-port
      - "${CELESTIA_NODE_RPC_PORT:-26657}"
      - --celestia.rpc
      - "${CELESTIA_RPC:-}"
      - --log-level
      - "DEBUG"

  consensus:
    image: ghcr.io/conduitxyz/plume-nitro:v3.3.2-celestia
    restart: unless-stopped
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL:-}
      - ETH_BEACON_RPC_URL=${ETH_BEACON_RPC_URL:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - EXTRA_FLAGS=${EXTRA_FLAGS:-}
    ports:
      - ${P2P_PORT:-30303}:30303/tcp
      - ${P2P_PORT:-30303}:30303/udp
    <<: *logging
    volumes:
      - plume-data:/home/user/.arbitrum
    entrypoint:
      - /usr/local/bin/nitro
      - --validation.wasm.allowed-wasm-module-roots
      - /home/user/nitro-legacy/machines,/home/user/target/machines
      - --chain.id=98866
      - --chain.name=conduit-orbit-deployer
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.port=${RPC_PORT:-8545}
      - --http.api=net,web3,eth,txpool,debug,admin,arb,arbdebug,arbtrace
      - --ws.expose-all
      - --ws.rpcprefix=/
      - --ws.port=${WS_PORT:-8546}
      - --ws.addr=0.0.0.0
      - --ws.origins=*
      - --ws.api=net,web3,eth,txpool,debug
      - "--chain.info-json=[{\"chain-id\":98866,\"parent-chain-id\":1,\"chain-name\":\"conduit-orbit-deployer\",\"chain-config\":{\"chainId\":98866,\"homesteadBlock\":0,\"daoForkBlock\":null,\"daoForkSupport\":true,\"eip150Block\":0,\"eip150Hash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"eip155Block\":0,\"eip158Block\":0,\"byzantiumBlock\":0,\"constantinopleBlock\":0,\"petersburgBlock\":0,\"istanbulBlock\":0,\"muirGlacierBlock\":0,\"berlinBlock\":0,\"londonBlock\":0,\"clique\":{\"period\":0,\"epoch\":0},\"arbitrum\":{\"EnableArbOS\":true,\"AllowDebugPrecompiles\":false,\"DataAvailabilityCommittee\":true,\"InitialArbOSVersion\":32,\"InitialChainOwner\":\"0x5Ec32984332eaB190cA431545664320259D755d8\",\"GenesisBlockNum\":0}},\"rollup\":{\"bridge\":\"0x35381f63091926750F43b2A7401B083263aDEF83\",\"inbox\":\"0x943fc691242291B74B105e8D19bd9E5DC2fcBa1D\",\"sequencer-inbox\":\"0x85eC1b9138a8b9659A51e2b51bb0861901040b59\",\"rollup\":\"0x35c60Cc77b0A8bf6F938B11bd3E9D319a876c2aC\",\"validator-utils\":\"0x84eA2523b271029FFAeB58fc6E6F1435a280db44\",\"validator-wallet-creator\":\"0x0A5eC2286bB15893d5b8f320aAbc823B2186BA09\",\"deployed-at\":21887008}}]"
      - --node.celestia-cfg.enable=true
      - --node.celestia-cfg.url=http://celestia-server:${CELESTIA_NODE_RPC_PORT:-26657}
      - --node.data-availability.enable=true
      - --node.data-availability.rest-aggregator.enable=true
      - --node.data-availability.rest-aggregator.urls=https://das-plume-mainnet-1.t.conduit.xyz
      - --execution.forwarding-target=https://rpc.plume.org
      - --execution.caching.archive
      - --parent-chain.connection.url=${ETH_RPC_URL:-}
      - --parent-chain.blob-client.beacon-url=${ETH_BEACON_RPC_URL:-}
      - --node.staker.enable=false
      - --node.feed.input.url=wss://relay-plume-mainnet-1.t.conduit.xyz
      - --node.sequencer=false
      - --execution.rpc.tx-fee-cap=100
      - --execution.rpc.gas-cap=500000000
      - --metrics
      - --metrics-server.addr=0.0.0.0
      - --metrics-server.port=${METRICS_PORT:-6070}
      - --metrics-server.update-interval=5s
    labels:
      - traefik.enable=true
      # RPC Router
      - traefik.http.routers.${RPC_HOST:-plume-rpc}.service=${RPC_HOST:-plume-rpc}
      - traefik.http.routers.${RPC_HOST:-plume-rpc}.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-plume-rpc}.rule=Host(`${RPC_HOST:-plume-rpc}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-plume-rpc}.tls.certresolver=letsencrypt
      - traefik.http.routers.${RPC_HOST:-plume-rpc}lb.service=${RPC_HOST:-plume-rpc}
      - traefik.http.routers.${RPC_HOST:-plume-rpc}lb.entrypoints=websecure
      - traefik.http.routers.${RPC_HOST:-plume-rpc}lb.rule=Host(`${RPC_LB:-plume-lb}.${DOMAIN}`)
      - traefik.http.routers.${RPC_HOST:-plume-rpc}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${RPC_HOST:-plume-rpc}.loadbalancer.server.port=${RPC_PORT:-8545}
      # WS Router
      - traefik.http.routers.${WS_HOST:-plume-ws}.service=${WS_HOST:-plume-ws}
      - traefik.http.routers.${WS_HOST:-plume-ws}.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-plume-ws}.rule=Host(`${WS_HOST:-plume-ws}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-plume-ws}.tls.certresolver=letsencrypt
      - traefik.http.routers.${WS_HOST:-plume-ws}lb.service=${WS_HOST:-plume-ws}
      - traefik.http.routers.${WS_HOST:-plume-ws}lb.entrypoints=websecure
      - traefik.http.routers.${WS_HOST:-plume-ws}lb.rule=Host(`${WS_LB:-plume-ws-lb}.${DOMAIN}`)
      - traefik.http.routers.${WS_HOST:-plume-ws}lb.tls.certresolver=letsencrypt
      - traefik.http.services.${WS_HOST:-plume-ws}.loadbalancer.server.port=${WS_PORT:-8546}

volumes:
  plume-data:
