x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  consensus:
    build:
      context: ./plume-build
    image: plume:local
    user: "${USERNAME:-user}"
    restart: unless-stopped
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL:-}
      - ETH_BEACON_RPC_URL=${ETH_BEACON_RPC_URL:-}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - EXTRA_FLAGS=${EXTRA_FLAGS:-}
    ports:
      - ${P2P_PORT:-30303}:30303/tcp
      - ${P2P_PORT:-30303}:30303/udp
    <<: *logging
    volumes:
      - arbitrum-data:/home/user/.arbitrum
    command:
      - "--http.api=net,web3,eth,debug"
      - "--http.corsdomain=*"
      - "--http.addr=0.0.0.0"
      - "--http.vhosts=*"
      - "--http.port=${RPC_PORT:-8545}"
      - "--ws.port=${WS_PORT:-8546}"
      - "--ws.addr=0.0.0.0"
      - "--ws.origins=*"
      - "--parent-chain.connection.url=${ETH_RPC_URL:-}"
      - "--parent-chain.blob-client.beacon-url=${ETH_BEACON_RPC_URL:-}"
      - "--metrics"
      - "--metrics-server.addr=127.0.0.1"
      - "--metrics-server.port=${METRICS_PORT:-6070}"
      - "--metrics-server.update-interval=5s"
      - "--chain.id=98866"
      - "--chain.info-json=[{\"chain-id\":98866,\"parent-chain-id\":1,\"chain-name\":\"conduit-orbit-deployer\",\"chain-config\":{\"chainId\":98866,\"homesteadBlock\":0,\"daoForkBlock\":null,\"daoForkSupport\":true,\"eip150Block\":0,\"eip150Hash\":\"0x0000000000000000000000000000000000000000000000000000000000000000\",\"eip155Block\":0,\"eip158Block\":0,\"byzantiumBlock\":0,\"constantinopleBlock\":0,\"petersburgBlock\":0,\"istanbulBlock\":0,\"muirGlacierBlock\":0,\"berlinBlock\":0,\"londonBlock\":0,\"clique\":{\"period\":0,\"epoch\":0},\"arbitrum\":{\"EnableArbOS\":true,\"AllowDebugPrecompiles\":false,\"DataAvailabilityCommittee\":true,\"InitialArbOSVersion\":32,\"InitialChainOwner\":\"0x5Ec32984332eaB190cA431545664320259D755d8\",\"GenesisBlockNum\":0}},\"rollup\":{\"bridge\":\"0x35381f63091926750F43b2A7401B083263aDEF83\",\"inbox\":\"0x943fc691242291B74B105e8D19bd9E5DC2fcBa1D\",\"sequencer-inbox\":\"0x85eC1b9138a8b9659A51e2b51bb0861901040b59\",\"rollup\":\"0x35c60Cc77b0A8bf6F938B11bd3E9D319a876c2aC\",\"validator-utils\":\"0x84eA2523b271029FFAeB58fc6E6F1435a280db44\",\"validator-wallet-creator\":\"0x0A5eC2286bB15893d5b8f320aAbc823B2186BA09\",\"deployed-at\":21887008}}]"
      - "--chain.name=conduit-orbit-deployer"
      - "--execution.caching.archive"
      - "--execution.forwarding-target=https://phoenix-rpc.plumenetwork.xyz"
      - "--node.data-availability.enable=true"
      - "--node.data-availability.rest-aggregator.enable=true"
      - "--node.data-availability.rest-aggregator.urls=https://das-plume-mainnet-1.t.conduit.xyz"
      - "--node.staker.enable=false"
      - "--node.feed.input.url=wss://relay-plume-mainnet-1.t.conduit.xyz"
    labels:
      - traefik.enable=true
      # RPC Router
      - traefik.http.routers.${PLUME_RPC_HOST:-plume-rpc}.service=${PLUME_RPC_HOST:-plume-rpc}
      - traefik.http.routers.${PLUME_RPC_HOST:-plume-rpc}.entrypoints=websecure
      - traefik.http.routers.${PLUME_RPC_HOST:-plume-rpc}.rule=Host(`${PLUME_RPC_HOST:-plume-rpc}.${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.${PLUME_RPC_HOST:-plume-rpc}.tls.certresolver=letsencrypt
      - traefik.http.services.${PLUME_RPC_HOST:-plume-rpc}.loadbalancer.server.port=${RPC_PORT:-8545}
      # WS Router
      - traefik.http.routers.${PLUME_WS_HOST:-plume-ws}.service=${PLUME_WS_HOST:-plume-ws}
      - traefik.http.routers.${PLUME_WS_HOST:-plume-ws}.entrypoints=websecure
      - traefik.http.routers.${PLUME_WS_HOST:-plume-ws}.rule=Host(`${PLUME_WS_HOST:-plume-ws}.${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.${PLUME_WS_HOST:-plume-ws}.tls.certresolver=letsencrypt
      - traefik.http.services.${PLUME_WS_HOST:-plume-ws}.loadbalancer.server.port=${WS_PORT:-8546}

volumes:
  arbitrum-data:
